# Generated by Django 5.2.7 on 2025-10-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date', 'time'], 'permissions': [('can_confirm_reservation', 'Può confermare prenotazioni'), ('can_delete_any_reservation', 'Può eliminare qualsiasi prenotazione'), ('can_view_all_reservations', 'Può visualizzare tutte le prenotazioni')]},
        ),
    ]
